// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/authority.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Brochure.AuthorityService {
  public static partial class AuthorityService
  {
    static readonly string __ServiceName = "Brochure.AuthorityService.AuthorityService";


    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Brochure.AuthorityService.AuthorityReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AuthorityService</summary>
    [grpc::BindServiceMethod(typeof(AuthorityService), "BindService")]
    public abstract partial class AuthorityServiceBase
    {
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AuthorityServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder().Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuthorityServiceBase serviceImpl)
    {
    }

  }
}
#endregion
