// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/authority.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Brochure.AuthorityService {
  public static partial class AuthorityService
  {
    static readonly string __ServiceName = "Brochure.AuthorityService.AuthorityService";

    static readonly grpc::Marshaller<global::Brochure.AuthorityService.Params> __Marshaller_Brochure_AuthorityService_Params = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Brochure.AuthorityService.Params.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Brochure.AuthorityService.Authority> __Marshaller_Brochure_AuthorityService_Authority = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Brochure.AuthorityService.Authority.Parser.ParseFrom);

    static readonly grpc::Method<global::Brochure.AuthorityService.Params, global::Brochure.AuthorityService.Authority> __Method_GetAuthorityList = new grpc::Method<global::Brochure.AuthorityService.Params, global::Brochure.AuthorityService.Authority>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAuthorityList",
        __Marshaller_Brochure_AuthorityService_Params,
        __Marshaller_Brochure_AuthorityService_Authority);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Brochure.AuthorityService.AuthorityReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AuthorityService</summary>
    [grpc::BindServiceMethod(typeof(AuthorityService), "BindService")]
    public abstract partial class AuthorityServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Brochure.AuthorityService.Authority> GetAuthorityList(global::Brochure.AuthorityService.Params request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AuthorityService</summary>
    public partial class AuthorityServiceClient : grpc::ClientBase<AuthorityServiceClient>
    {
      /// <summary>Creates a new client for AuthorityService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AuthorityServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AuthorityService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AuthorityServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AuthorityServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AuthorityServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Brochure.AuthorityService.Authority GetAuthorityList(global::Brochure.AuthorityService.Params request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAuthorityList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Brochure.AuthorityService.Authority GetAuthorityList(global::Brochure.AuthorityService.Params request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAuthorityList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Brochure.AuthorityService.Authority> GetAuthorityListAsync(global::Brochure.AuthorityService.Params request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAuthorityListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Brochure.AuthorityService.Authority> GetAuthorityListAsync(global::Brochure.AuthorityService.Params request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAuthorityList, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AuthorityServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AuthorityServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AuthorityServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAuthorityList, serviceImpl.GetAuthorityList).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AuthorityServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAuthorityList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Brochure.AuthorityService.Params, global::Brochure.AuthorityService.Authority>(serviceImpl.GetAuthorityList));
    }

  }
}
#endregion
