// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/roles.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Proto.Roles.Grpc {
  public static partial class RolesService
  {
    static readonly string __ServiceName = "Proto.Roles.Grpc.RolesService";

    static readonly grpc::Marshaller<global::Proto.Roles.Grpc.RolesRequest> __Marshaller_Proto_Roles_Grpc_RolesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Roles.Grpc.RolesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Roles.Grpc.RolesResponse> __Marshaller_Proto_Roles_Grpc_RolesResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Roles.Grpc.RolesResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Roles.Grpc.FailIdsResponse> __Marshaller_Proto_Roles_Grpc_FailIdsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Roles.Grpc.FailIdsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Roles.Grpc.MutiRolesRequest> __Marshaller_Proto_Roles_Grpc_MutiRolesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Roles.Grpc.MutiRolesRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.RolesResponse> __Method_GetRoles = new grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.RolesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRoles",
        __Marshaller_Proto_Roles_Grpc_RolesRequest,
        __Marshaller_Proto_Roles_Grpc_RolesResponse);

    static readonly grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.FailIdsResponse> __Method_DeleteRoles = new grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.FailIdsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteRoles",
        __Marshaller_Proto_Roles_Grpc_RolesRequest,
        __Marshaller_Proto_Roles_Grpc_FailIdsResponse);

    static readonly grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.FailIdsResponse> __Method_UpdateRoles = new grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.FailIdsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateRoles",
        __Marshaller_Proto_Roles_Grpc_RolesRequest,
        __Marshaller_Proto_Roles_Grpc_FailIdsResponse);

    static readonly grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.RolesResponse> __Method_Insert = new grpc::Method<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.RolesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Insert",
        __Marshaller_Proto_Roles_Grpc_RolesRequest,
        __Marshaller_Proto_Roles_Grpc_RolesResponse);

    static readonly grpc::Method<global::Proto.Roles.Grpc.MutiRolesRequest, global::Proto.Roles.Grpc.RolesResponse> __Method_InsertMuti = new grpc::Method<global::Proto.Roles.Grpc.MutiRolesRequest, global::Proto.Roles.Grpc.RolesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InsertMuti",
        __Marshaller_Proto_Roles_Grpc_MutiRolesRequest,
        __Marshaller_Proto_Roles_Grpc_RolesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Proto.Roles.Grpc.RolesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RolesService</summary>
    [grpc::BindServiceMethod(typeof(RolesService), "BindService")]
    public abstract partial class RolesServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Proto.Roles.Grpc.RolesResponse> GetRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Proto.Roles.Grpc.FailIdsResponse> DeleteRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Proto.Roles.Grpc.FailIdsResponse> UpdateRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Proto.Roles.Grpc.RolesResponse> Insert(global::Proto.Roles.Grpc.RolesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Proto.Roles.Grpc.RolesResponse> InsertMuti(global::Proto.Roles.Grpc.MutiRolesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RolesService</summary>
    public partial class RolesServiceClient : grpc::ClientBase<RolesServiceClient>
    {
      /// <summary>Creates a new client for RolesService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RolesServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RolesService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RolesServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RolesServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RolesServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Proto.Roles.Grpc.RolesResponse GetRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRoles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Roles.Grpc.RolesResponse GetRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRoles, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.RolesResponse> GetRolesAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRolesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.RolesResponse> GetRolesAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRoles, null, options, request);
      }
      public virtual global::Proto.Roles.Grpc.FailIdsResponse DeleteRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRoles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Roles.Grpc.FailIdsResponse DeleteRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteRoles, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.FailIdsResponse> DeleteRolesAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteRolesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.FailIdsResponse> DeleteRolesAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteRoles, null, options, request);
      }
      public virtual global::Proto.Roles.Grpc.FailIdsResponse UpdateRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRoles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Roles.Grpc.FailIdsResponse UpdateRoles(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateRoles, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.FailIdsResponse> UpdateRolesAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateRolesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.FailIdsResponse> UpdateRolesAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateRoles, null, options, request);
      }
      public virtual global::Proto.Roles.Grpc.RolesResponse Insert(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Insert(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Roles.Grpc.RolesResponse Insert(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Insert, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.RolesResponse> InsertAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.RolesResponse> InsertAsync(global::Proto.Roles.Grpc.RolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Insert, null, options, request);
      }
      public virtual global::Proto.Roles.Grpc.RolesResponse InsertMuti(global::Proto.Roles.Grpc.MutiRolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertMuti(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Roles.Grpc.RolesResponse InsertMuti(global::Proto.Roles.Grpc.MutiRolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertMuti, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.RolesResponse> InsertMutiAsync(global::Proto.Roles.Grpc.MutiRolesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InsertMutiAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Roles.Grpc.RolesResponse> InsertMutiAsync(global::Proto.Roles.Grpc.MutiRolesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertMuti, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RolesServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RolesServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RolesServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetRoles, serviceImpl.GetRoles)
          .AddMethod(__Method_DeleteRoles, serviceImpl.DeleteRoles)
          .AddMethod(__Method_UpdateRoles, serviceImpl.UpdateRoles)
          .AddMethod(__Method_Insert, serviceImpl.Insert)
          .AddMethod(__Method_InsertMuti, serviceImpl.InsertMuti).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RolesServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetRoles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.RolesResponse>(serviceImpl.GetRoles));
      serviceBinder.AddMethod(__Method_DeleteRoles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.FailIdsResponse>(serviceImpl.DeleteRoles));
      serviceBinder.AddMethod(__Method_UpdateRoles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.FailIdsResponse>(serviceImpl.UpdateRoles));
      serviceBinder.AddMethod(__Method_Insert, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Roles.Grpc.RolesRequest, global::Proto.Roles.Grpc.RolesResponse>(serviceImpl.Insert));
      serviceBinder.AddMethod(__Method_InsertMuti, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.Roles.Grpc.MutiRolesRequest, global::Proto.Roles.Grpc.RolesResponse>(serviceImpl.InsertMuti));
    }

  }
}
#endregion
